### ISSUE TITLE
Spracovanie katalógu požiadaviek

### ISSUE THREAD

**Issue by SamuelJesik** [TIS2023-FMFI/sledovanie-prace#2]

**Comment by SamuelJesik** [comment]
Spracovanie hotové.

**Comment by pavelpetrovic** [comment]
mojich par drobnych pripomienok
vyrobte vybornu novu verziu a poslite mi ju cez teams, aby som ju co najskor skontroloval
najneskor to urobim na nasom stretnuti.


1.2. je minimalisticke, mozete pridat este vetu-dve

1.4. cokolvek, co sa da pridat potesi

2.2. ked uz pisem, ze tri typy,
tak to nemozem nechat tak a musim
vysvetlit aky

System umoznuje rozdelenie na tri rozne typy pouzıvatelov: taky, onaky, fialovy. 

je umoˇznen´a  => co najmenej
trpneho rodu
"pouzivatel si moze vytvorit..."

umozni moznost - neprehante to s formulaciami...

vytvoriˇt, modifikovaˇt alebo vybraˇ  => nerozumiem
co to znamena modifikovat?
aky je rozdiel medzi vybrat?

casova os - netusim co to je

grafy a ˇstatistiky relevantn´e pre projekty - vobec netusim o com je rec

kalend´arov´y pohˇlad - vobec netusim co to je

pozvaˇt pracovn´ıkov - naozaj pozvat? pozvat znamena, ze musi clovek potvrdit invite, ak ich tam priamo zaraduje, tak ich nepozyva

pridelovaˇt im pr´acu - co si mam za tym predstavit?

co sa bude dat exportovat?

2.3. rovno napiste kto, co, netreba zvlast vymenovat a potom napisat

malo by byt jasne, ci "Admnistrator" je jeden konkretny pouzivatel, alebo trieda pouzivatelov, teda mozno vyrobit viacej adminov

vo svojom t´ıme - o time doteraz vobec nebola rec, dostal som facku

vˇsetkej pr´ace na projektoch
 => nerozumiem.  mysli sa vsetkej prace na zvolenom projekte?
 
 spravuje jeden admin vsetky projekty? 
 
 zad´avaˇt pr´acu pracovn´ıkom 
  => vobec nerozumiem
  
 ˇcas, ktor´y m´a jej urobenie trvaˇt => malo rozumiem, iba
 tipujem co to asi znamena
 a nikde nevidim, ako si to vie konfrontovat s realitou
 
 Syst´em m´a pr´ıstup
k PostgreSQL datab´aze.
 => to znie ako keby uz DB existovala a system k nej dostane pristup
 
 Uˇz´ıvateˇl mˆoˇze => prihlaseny pouzivatel?
 alebo skor po prihlaseni do systemu?
 
 Uˇz´ıvateˇl mˆoˇze kedykoˇlvek zastaviˇt sledovanie ˇcasu
 => to znamena pocas celej prace bol prihlaseny a ma otvorenu stranku, kde mu prihlasenie neeppirovalo a inak to zastavit nemoze, alebo je to inak?
 
 nic neprotireci tomu,
 ze na projekte je len jeden
 zaciatok a jeden koniec
 
 3.1.4. ale predsa iba admin
 to moze
 
 3.1.5. nepotrebujem
 ale vsade kde nejaka poziadavka
 nieco umoznuje, tak treba vzdy ze kto moze co
 
 
 z 2.3. nevidno, ze admin moze tiez fungovat v roli zakaznika
 
 3.1.6.  nie je poziadavka 
 na funkcionalitu => presunut
 do samostatnej casti na konci
 "poziadavky nevztahujuce sa na funkcionalitu"
 
 3.1.7.  presne uviest ktore udaje sa exportuju, moznost
 odkazat sa na prilohu, alebo iny odkaz
 
 3.1.8 nerozumiem
 
 3.1.9. tu sa prvy raz dozvedame,
 ze existuju ulohy, ale pracovnik nezadava pracu na ulohach ale na projektoch
 podla 3.1.1 => nekonzistentnost
 
 3.1.10 nie ze obsahuje,
 ale pouzivatel nemoze robit ziadne akcie v systeme bez toho aby sa neprihlasil => ako sa prihlasuje? meno/mail/heslo?
 
 3.1.12. ako? kto? ake presne 
 vsetky udaje vyplni?
 
 3.1.13. co vsetko moze upravovat
 a kto? 
 
 3.1.14. prvykrat vidim prestoje
 a vobec netusim co to znamena
 a kde sa to zadava a co znamena
 ze zobrazuje a komu??
 
 3.1.15. vsetky pohlady treba
 presne popisat co na nich vidno
