### ISSUE TITLE
Katalóg požiadaviek - kapitola "Úvod"

### ISSUE THREAD

**Issue by AdamHuserka** [TIS2023-FMFI/sledovanie-prace#3]
Prvá kapitola katalógu požiadaviek, ktorá má obsahovať:  
- Účel dokumentu požiadaviek
- Rozsah využitia systému
- Slovník pojmov
- Referencie
- Prehľad zvyšku dokumentu

**Comment by AdamHuserka** [comment]
[Katalóg___Úvod.pdf](https://github.com/TIS2023-FMFI/sledovanie-prace/files/12909972/Katalog___Uvod.pdf)

Prvotná verzia Úvodu

**Comment by SamuelJesik** [comment]
Doplnené @T3odor10001  + @SamuelJesik

**Comment by AdamHuserka** [comment]
Začínam upravovať úvod

**Comment by AdamHuserka** [comment]
Odkaz na Google Document: https://docs.google.com/document/d/1M0OjeMVJ1aBanI8q9Fy-Idm0IK-bElm_emJhDSwY180/edit?usp=share_link
