### ISSUE TITLE
Katalóg požiadaviek - kapitola "Všeobecný popis"

### ISSUE THREAD

**Issue by AdamHuserka** [TIS2023-FMFI/sledovanie-prace#4]
Druhá kapitola katalógu požiadaviek, ktorá má obsahovať:
- Perspektíva systému
- Funkcie systému
- Charakteristika používateľov
- Všeobecné obmedzenia
- Predpoklady a závislosti

**Comment by AdamHuserka** [comment]
[Katalóg___Všeobecný_popis.pdf](https://github.com/TIS2023-FMFI/sledovanie-prace/files/12913690/Katalog___Vseobecny_popis.pdf)

Prvotná nedokončená verzia všeobecného popisu, bude potrebné stretnutie tímu aby sme konzultovali a upravili niekoľko častí.

**Comment by SamuelJesik** [comment]
Doplnené @T3odor10001  + @SamuelJesik
