### ISSUE TITLE
Katalóg požiadaviek - kapitola "Špecifické požiadavky"

### ISSUE THREAD

**Issue by AdamHuserka** [TIS2023-FMFI/sledovanie-prace#5]
Tretia kapitola katalógu požiadaviek, ktorá má no aj nemusí obsahovať:
- Funkčné požiadavky
- Požiadavky, ktoré sa nevzťahujú na funkcionalitu
- Požiadavky ohľadom rozhrania

**Comment by pavelpetrovic** [comment]
len malý komentár: ako som na prednáške upozorňoval, je nevhodné non-functional requirements prekladať ako "nefunkčné požiadavky". Sú to "požiadavky, ktoré sa nevzťahujú na funkcionalitu", alebo "ostatné požiadavky".

**Comment by AdamHuserka** [comment]
Ďakujem za upozornenie, editoval som popis Issue

**Comment by SamuelJesik** [comment]
Doplnené @T3odor10001  + @SamuelJesik
